//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BartenderCalculator.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BartenderCalculator.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ConfigurationView_ProductNamePlaceholder {
            get {
                return ResourceManager.GetString("ConfigurationView.ProductNamePlaceholder", resourceCulture);
            }
        }
        
        internal static string ConfigurationVew_NewProductHeadline {
            get {
                return ResourceManager.GetString("ConfigurationVew.NewProductHeadline", resourceCulture);
            }
        }
        
        internal static string ConfigurationView_TabText {
            get {
                return ResourceManager.GetString("ConfigurationView.TabText", resourceCulture);
            }
        }
        
        internal static string ConfigurationView_AddProductButton {
            get {
                return ResourceManager.GetString("ConfigurationView.AddProductButton", resourceCulture);
            }
        }
        
        internal static string ConfigurationView_Table_NameHeadline {
            get {
                return ResourceManager.GetString("ConfigurationView.Table.NameHeadline", resourceCulture);
            }
        }
        
        internal static string ConfigurationView_Table_PriceHeadline {
            get {
                return ResourceManager.GetString("ConfigurationView.Table.PriceHeadline", resourceCulture);
            }
        }
        
        internal static string ConfigurationView_ProductPrice_Placeholder {
            get {
                return ResourceManager.GetString("ConfigurationView.ProductPrice.Placeholder", resourceCulture);
            }
        }
        
        internal static string OrderView_TabText {
            get {
                return ResourceManager.GetString("OrderView.TabText", resourceCulture);
            }
        }
        
        internal static string OrderView_AvailableProducts_Headline {
            get {
                return ResourceManager.GetString("OrderView.AvailableProducts.Headline", resourceCulture);
            }
        }
        
        internal static string OrderView_CurrentOrder_Headline {
            get {
                return ResourceManager.GetString("OrderView.CurrentOrder.Headline", resourceCulture);
            }
        }
        
        internal static string OrderView_CurrentOder_ClearButton {
            get {
                return ResourceManager.GetString("OrderView.CurrentOder.ClearButton", resourceCulture);
            }
        }
        
        internal static string OderView_CurrentOrder_ProductNameColumn {
            get {
                return ResourceManager.GetString("OderView.CurrentOrder.ProductNameColumn", resourceCulture);
            }
        }
        
        internal static string OrderView_CurrentOrder_PriceColumn {
            get {
                return ResourceManager.GetString("OrderView.CurrentOrder.PriceColumn", resourceCulture);
            }
        }
        
        internal static string OrderView_CurrentOder_QuantityColumn {
            get {
                return ResourceManager.GetString("OrderView.CurrentOder.QuantityColumn", resourceCulture);
            }
        }
        
        internal static string Alert_WarningHeadline {
            get {
                return ResourceManager.GetString("Alert.WarningHeadline", resourceCulture);
            }
        }
        
        internal static string Alert_ProductSameNameExistsText {
            get {
                return ResourceManager.GetString("Alert.ProductSameNameExistsText", resourceCulture);
            }
        }
        
        internal static string Alert_InvalidProductNameHeadline {
            get {
                return ResourceManager.GetString("Alert.InvalidProductNameHeadline", resourceCulture);
            }
        }
        
        internal static string Alert_OkButton {
            get {
                return ResourceManager.GetString("Alert.OkButton", resourceCulture);
            }
        }
        
        internal static string Alert_InvalidProductNameText {
            get {
                return ResourceManager.GetString("Alert.InvalidProductNameText", resourceCulture);
            }
        }
        
        internal static string Alert_InvalidProductPriceHeadline {
            get {
                return ResourceManager.GetString("Alert.InvalidProductPriceHeadline", resourceCulture);
            }
        }
        
        internal static string Alert_InvalidProductPrice_Text {
            get {
                return ResourceManager.GetString("Alert.InvalidProductPrice.Text", resourceCulture);
            }
        }
    }
}
